### ISSUE TITLE
Apply Label to Generated Features for Roadmap Creation

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/jirai#4]
Create an "Add a Label" Button on the Feature Review Screen. This can be used to create and assign labels which are assigned to every issue created in Jira. 

Users can go on to create an Advanced Roadmap from this label — instantly seeing their created feature(s) in the roadmap view.

- [ ] explore if its possible to create a roadmap by label programmatically
- [ ] create UI and state for label creation, assignment, and application during `POST` of issues
  - [ ] create UI
  - [ ] create label `api/v1/route` and `POST` to Jira
  - [ ] update issues object with field
  - [ ] `POST` issues with added label
  - [ ] `PUT` issues with latest date if already created
